services:
  - type: web
    runtime: static
    name: tuinbooks-v2
    buildCommand: npm install && npm run check
    staticPublishPath: ./dist
    routes:
      - type: redirect
        source: /app
        destination: /app/
      - type: redirect
        source: /management
        destination: /management/
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
