import { supabase } from '../../lib/supabase.js';
import type { CompleteVisitInput, FieldOpportunity, MobileContext, OpportunityInput, WorkDay, WorkRecord, WorkTaskOutcome } from '../../domain/types.js';

export async function loadWorkDay(businessId:string,date:WorkDay['date']):Promise<WorkDay>{
  const {data,error}=await supabase.rpc('tuinbooks_v2_load_work_day',{p_business_id:businessId,p_date:date});if(error)throw error;return normaliseWorkDay(data,date);
}
export async function loadMobileContext():Promise<MobileContext|null>{const {data,error}=await supabase.rpc('tuinbooks_v2_mobile_context');if(error)throw error;if(!data)return null;return{businessId:String(data.business_id),businessName:String(data.business_name??'TuinBooks'),userId:String(data.user_id??''),displayName:String(data.display_name??''),profile:String(data.profile)==='owner_mobile'?'owner_mobile':'field_worker',assignedTeamIds:Array.isArray(data.assigned_team_ids)?data.assigned_team_ids.map(String):[]};}
export async function completeVisit(businessId:string,input:CompleteVisitInput):Promise<string>{const {data,error}=await supabase.rpc('tuinbooks_v2_complete_visit',{p_business_id:businessId,p_submission_id:input.submissionId,p_work_record_id:input.workRecordId,p_schedule_id:input.visitId,p_task_outcomes:input.taskOutcomes,p_note:input.note,p_photo_paths:input.photoPaths});if(error)throw error;return String(data);}
export async function createOpportunity(businessId:string,input:OpportunityInput):Promise<string>{const {data,error}=await supabase.rpc('tuinbooks_v2_create_opportunity',{p_business_id:businessId,p_id:input.id,p_schedule_id:input.visitId,p_work_record_id:input.workRecordId,p_category:input.category,p_note:input.note,p_photo_paths:input.photoPaths});if(error)throw error;return String(data);}
export async function uploadWorkPhotos(businessId:string,teamId:string,visitId:string,files:File[]):Promise<string[]>{const paths:string[]=[];for(const file of files){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${businessId}/${teamId}/v2/${visitId}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('tuinbooks-media').upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(error)throw error;paths.push(path);}return paths;}
export async function signedPhotoUrl(path:string):Promise<string|null>{const {data,error}=await supabase.storage.from('tuinbooks-media').createSignedUrl(path,600);if(error)return null;return data?.signedUrl??null;}
export async function reviewOpportunity(businessId:string,opportunityId:string,decision:'quote-created'|'site-visit'|'design-consult'|'defer'|'closed',linkedQuoteId:string|null=null,note=''):Promise<void>{const{error}=await supabase.rpc('tuinbooks_v2_review_opportunity',{p_business_id:businessId,p_opportunity_id:opportunityId,p_decision:decision,p_linked_quote_id:linkedQuoteId,p_note:note});if(error)throw error;}
function normaliseWorkDay(raw:any,date:WorkDay['date']):WorkDay{return{date,teams:Array.isArray(raw?.teams)?raw.teams.map((r:any)=>({id:String(r.id),businessId:String(r.business_id),name:String(r.name??'Team'),active:r.active!==false,capacityHours:Number(r.capacity_hours??8),bufferHours:Number(r.buffer_hours??0)})):[],accounts:Array.isArray(raw?.accounts)?raw.accounts.map((r:any)=>({id:String(r.id),businessId:String(r.business_id),name:String(r.name??'Client'),status:String(r.status??'active'),contactName:String(r.contact_name??''),phone:String(r.phone??''),email:String(r.email??'')})):[],locations:Array.isArray(raw?.locations)?raw.locations.map((r:any)=>({id:String(r.id),businessId:String(r.business_id),accountId:String(r.customer_id),siteName:String(r.site_name??''),address:String(r.address??''),suburb:String(r.suburb??''),accessNotes:String(r.access_notes??''),instructions:String(r.instructions??''),active:r.active!==false})):[],visits:Array.isArray(raw?.visits)?raw.visits.map((r:any)=>({id:String(r.id),businessId:String(r.business_id),date:String(r.visit_date),accountId:String(r.client_id),serviceLocationId:String(r.payload?.serviceSiteId??r.payload?.service_site_id??'')||null,teamId:String(r.team_id),status:String(r.status??'scheduled'),estimatedMinutes:Math.max(0,Math.round(Number(r.estimated_hours??0)*60)),sortOrder:Number(r.sort_order??0),serviceIds:Array.isArray(r.service_ids)?r.service_ids.map(String):[],visitType:String(r.payload?.visitType)==='additional'?'additional':String(r.payload?.visitType)==='quoted'?'quoted':'routine',billingDisposition:String(r.payload?.billingDisposition??'routine') as any,seriesId:null,seriesSlotId:null,occurrenceDate:null,recurrenceManualOverride:Boolean(r.payload?.manualOverride),payload:r.payload&&typeof r.payload==='object'?r.payload:{},updatedAt:r.updated_at??null})):[],workRecords:Array.isArray(raw?.work_records)?raw.work_records.map(normaliseWorkRecord):[],opportunities:Array.isArray(raw?.opportunities)?raw.opportunities.map(normaliseOpportunity):[],clientHolds:Array.isArray(raw?.holds)?raw.holds.map((r:any)=>({businessId:String(r.business_id),clientId:String(r.client_id),active:r.active!==false,reason:String(r.reason??'Do not service'),note:String(r.note??''),updatedAt:r.updated_at??null})):[],dayActions:Array.isArray(raw?.day_actions)?raw.day_actions.map((r:any)=>({id:String(r.id),businessId:String(r.business_id),date:String(r.calendar_date),teamId:String(r.team_id),kind:r.kind==='internal_event'?'internal_event':'team_note',title:String(r.title??''),detail:String(r.detail??''),time:String(r.calendar_time??''),status:String(r.status??'active'),response:String(r.response??''),resolvedAt:r.resolved_at??null,updatedAt:r.updated_at??null})):[]};}
function normaliseWorkRecord(r:any):WorkRecord{const tasks=Array.isArray(r.payload?.taskOutcomesV2)?r.payload.taskOutcomesV2:Array.isArray(r.payload?.taskOutcomesV56)?r.payload.taskOutcomesV56:[];return{id:String(r.id),businessId:String(r.business_id),scheduleJobId:r.schedule_job_id?String(r.schedule_job_id):null,accountId:String(r.client_id),serviceLocationId:String(r.payload?.serviceSiteId??'')||null,teamId:String(r.team_id),date:String(r.work_date) as WorkRecord['date'],tasks:tasks.map((x:any):WorkTaskOutcome=>({task:String(x.task??''),outcome:String(x.outcome??'Done') as any,note:String(x.note??'')})),extraDescription:String(r.extra_description??''),photoPaths:Array.isArray(r.photo_paths)?r.photo_paths.map(String):[],outcome:String(r.outcome??'Completed'),createdAt:r.created_at??null,payload:r.payload&&typeof r.payload==='object'?r.payload:{}};}
function normaliseOpportunity(r:any):FieldOpportunity{return{id:String(r.id),businessId:String(r.business_id),accountId:String(r.client_id),scheduleJobId:r.schedule_job_id?String(r.schedule_job_id):null,workRecordId:r.work_record_id?String(r.work_record_id):null,teamId:String(r.team_id),category:String(r.category??'Other'),note:String(r.note??''),photoPaths:Array.isArray(r.photo_paths)?r.photo_paths.map(String):[],status:String(r.status??'new'),reviewDecision:String(r.review_decision??'new'),createdAt:r.created_at??null,payload:r.payload&&typeof r.payload==='object'?r.payload:{}};}
