import { supabase } from '../../lib/supabase.js';
import type { Invoice, InvoiceInput, MoneyLine, MoneyWorkspace, Payment, PaymentInput, Quote, QuoteInput } from '../../domain/types.js';

export async function loadMoneyWorkspace(businessId:string):Promise<MoneyWorkspace>{const {data,error}=await supabase.rpc('tuinbooks_v2_load_money_workspace',{p_business_id:businessId});if(error)throw missing(error);return normalise(data,businessId);}
export async function saveQuote(businessId:string,input:QuoteInput):Promise<void>{await rpc('tuinbooks_v2_save_quote',{p_business_id:businessId,p_quote_id:input.id,p_client_id:input.accountId,p_quote_date:input.date,p_valid_until:input.validUntil,p_status:input.status,p_number:input.number,p_lines:input.lines,p_notes:input.notes});}
export async function setQuoteStatus(businessId:string,quoteId:string,status:string):Promise<void>{await rpc('tuinbooks_v2_set_quote_status',{p_business_id:businessId,p_quote_id:quoteId,p_status:status});}
export async function scheduleAcceptedQuote(businessId:string,quoteId:string):Promise<void>{await rpc('tuinbooks_v2_queue_accepted_quote',{p_business_id:businessId,p_quote_id:quoteId});}
export async function saveInvoice(businessId:string,input:InvoiceInput):Promise<void>{await rpc('tuinbooks_v2_save_invoice',{p_business_id:businessId,p_invoice_id:input.id,p_client_id:input.accountId,p_invoice_month:input.month,p_issue_date:input.issueDate,p_due_date:input.dueDate,p_status:input.status,p_number:input.number,p_lines:input.lines,p_notes:input.notes});}
export async function setVisitBillingAmount(businessId:string,visitId:string,amount:number):Promise<void>{await rpc('tuinbooks_v2_set_visit_billing_amount',{p_business_id:businessId,p_visit_id:visitId,p_amount:amount});}
export async function setInvoiceStatus(businessId:string,invoiceId:string,status:'Ready'|'Sent'|'Void'):Promise<void>{await rpc('tuinbooks_v2_set_invoice_status',{p_business_id:businessId,p_invoice_id:invoiceId,p_status:status});}
export async function createInvoiceFromFacts(businessId:string,accountId:string,month:string,issueDate:string,dueDate:string,visitIds:string[]):Promise<void>{await rpc('tuinbooks_v2_create_invoice_from_facts',{p_business_id:businessId,p_client_id:accountId,p_invoice_month:month,p_issue_date:issueDate,p_due_date:dueDate,p_visit_ids:visitIds});}
export async function recordPayment(businessId:string,input:PaymentInput):Promise<void>{await rpc('tuinbooks_v2_record_payment',{p_business_id:businessId,p_payment_id:input.id,p_invoice_id:input.invoiceId,p_date:input.date,p_amount:input.amount,p_method:input.method,p_reference:input.reference,p_note:input.note});}

export async function createPublicDocument(businessId:string,documentType:'quote'|'invoice'|'statement',documentId:string,accountId:string,snapshot:Record<string,unknown>,expiresAt:string):Promise<{token:string;expiresAt:string}>{const{data,error}=await supabase.rpc('tuinbooks_v2_create_public_document',{p_business_id:businessId,p_document_type:documentType,p_document_id:documentId,p_client_id:accountId,p_snapshot:snapshot,p_expires_at:expiresAt});if(error)throw missing(error);return{token:String(data?.token??''),expiresAt:String(data?.expires_at??expiresAt)};}

export async function reversePayment(businessId:string,paymentId:string,reason:string):Promise<void>{await rpc('tuinbooks_v2_reverse_payment',{p_business_id:businessId,p_payment_id:paymentId,p_reason:reason});}
function normalise(raw:any,businessId:string):MoneyWorkspace{return{accounts:(raw?.accounts??[]).map((r:any)=>({id:String(r.id),businessId,name:String(r.name??'Client'),status:String(r.status??'active'),contactName:String(r.contact_name??''),phone:String(r.phone??''),email:String(r.email??'')})),quotes:(raw?.quotes??[]).map((r:any)=>docQuote(r,businessId)),invoices:(raw?.invoices??[]).map((r:any)=>docInvoice(r,businessId)),payments:(raw?.payments??[]).map((r:any)=>({id:String(r.id),businessId,accountId:String(r.client_id),invoiceId:String(r.invoice_id),date:String(r.payment_date),amount:Number(r.amount??0),method:String(r.method??'Other'),reference:String(r.reference??''),note:String(r.note??''),reversedAt:r.reversed_at?String(r.reversed_at):null,createdAt:r.created_at?String(r.created_at):null})),billingFacts:(raw?.billing_facts??[]).map((r:any)=>({visitId:String(r.visit_id),accountId:String(r.client_id),date:String(r.visit_date),visitType:String(r.visit_type??'routine'),status:String(r.status??'scheduled'),billingDisposition:String(r.billing_disposition??'review'),description:String(r.description??'Garden service'),amount:r.amount==null?null:Number(r.amount),alreadyInvoiced:r.already_invoiced===true})),vatRegistered:raw?.vat_registered===true,defaultVatRate:Number(raw?.vat_rate??0),paymentTermsDays:Number(raw?.payment_terms_days??7),invoicePrefix:String(raw?.invoice_prefix??'INV-')};}
function docQuote(r:any,businessId:string):Quote{const p=obj(r.payload);return{id:String(r.id),businessId,accountId:String(r.client_id),date:String(r.quote_date??p.date??'2026-01-01') as Quote['date'],validUntil:p.validUntil?String(p.validUntil) as Quote['validUntil']:null,status:String(r.status??'Draft'),number:String(p.number??p.quote_number??r.id),lines:lines(p),notes:String(p.notes??''),acceptedAt:p.acceptedAt?String(p.acceptedAt):null,createdAt:r.created_at??null,updatedAt:r.updated_at??null};}
function docInvoice(r:any,businessId:string):Invoice{const p=obj(r.payload);return{id:String(r.id),businessId,accountId:String(r.client_id),month:String(r.invoice_month??''),number:String(r.invoice_number??'Draft'),issueDate:(p.issueDate??p.date)?String(p.issueDate??p.date) as Invoice['issueDate']:null,dueDate:p.dueDate?String(p.dueDate) as Invoice['dueDate']:null,status:String(r.status??'Draft'),lines:lines(p),notes:String(p.notes??''),createdAt:r.created_at??null,updatedAt:r.updated_at??null};}
function lines(p:Record<string,any>):MoneyLine[]{const raw=Array.isArray(p.lines)?p.lines:Array.isArray(p.lineItems)?p.lineItems:[];return raw.map((x:any,i:number)=>({id:String(x.id??`line-${i}`),description:String(x.description??x.name??'Line item'),quantity:Number(x.quantity??x.qty??1),unitPrice:Number(x.unitPrice??x.rate??x.price??0),vatRate:Number(x.vatRate??p.vatRate??0),discountPercent:Number(x.discountPercent??0),sourceVisitId:x.sourceVisitId?String(x.sourceVisitId):null,sourceQuoteId:x.sourceQuoteId?String(x.sourceQuoteId):null,category:String(x.category??(x.extra?'additional':'manual')) as MoneyLine['category']}));}
function obj(v:any):Record<string,any>{return v&&typeof v==='object'&&!Array.isArray(v)?v:{};}
async function rpc(name:string,args:Record<string,unknown>):Promise<void>{const {error}=await supabase.rpc(name,args);if(error)throw missing(error);}
function missing(error:any):Error{if(/does not exist|schema cache|PGRST20[25]|42883/i.test(String(error?.message??error)))return new Error('The TuinBooks v2 Money migration has not been installed in this database.');return error instanceof Error?error:new Error(String(error?.message??error));}
