import type { Account, ClientServiceHold, IsoDate, MoveVisitInput, ResizeVisitInput, ScheduleDayAction, ScheduleSeries, ScheduleWeek, ServiceLocation, Visit } from '../../domain/types.js';
import { activeHold, actionsForCell } from '../../domain/operations.js';
import { locationForVisit, nextSortOrder, normaliseDuration, sortOrderForIndex, visitsForCell } from '../../domain/schedule.js';
import { recurrenceLabel } from '../../domain/recurrence.js';
import { weekDays } from '../../domain/dates.js';

export interface CalendarController { destroy(): void; }
interface CalendarCallbacks{
  onMove:(move:MoveVisitInput)=>Promise<void>;
  onQueue:(visitId:string)=>Promise<void>;
  onResize:(input:ResizeVisitInput)=>Promise<void>;
  onAdd:(date:IsoDate,teamId:string,index:number,sortOrder:number)=>void;
  onVisitAction:(visit:Visit,account:Account|undefined,hold:ClientServiceHold|null)=>void;
  onDayAction:(kind:'team_note'|'internal_event',date:IsoDate,teamId:string,existing:ScheduleDayAction|null)=>void;
}
export function renderCalendar(container:HTMLElement,data:ScheduleWeek,callbacks:CalendarCallbacks):CalendarController{
  container.innerHTML='';const scroll=document.createElement('div');scroll.className='calendar-scroll';const grid=document.createElement('div');grid.className='calendar-grid';scroll.append(grid);container.append(scroll);
  const accountById=new Map<string,Account>(data.accounts.map(a=>[a.id,a]));const seriesById=new Map<string,ScheduleSeries>(data.series.map(s=>[s.id,s]));const days=weekDays(data.weekStart);const cleanup:Array<()=>void>=[];
  const corner=document.createElement('div');corner.className='calendar-corner';corner.textContent='Team';grid.append(corner);
  for(const day of days){const h=document.createElement('div');h.className='day-header';const d=new Date(`${day}T12:00:00`);h.innerHTML=`<span>${d.toLocaleDateString(undefined,{weekday:'short'})}</span><strong>${d.getDate()}</strong>`;grid.append(h);}
  for(const team of data.teams){const label=document.createElement('div');label.className='team-label';label.innerHTML=`<strong>${esc(team.name)}</strong><small>${team.capacityHours}h capacity</small>`;grid.append(label);
    for(const day of days){const cell=document.createElement('div');cell.className='schedule-cell';cell.dataset.scheduleCell='1';cell.dataset.date=day;cell.dataset.teamId=team.id;
      const actionBar=document.createElement('div');actionBar.className='day-action-bar';actionBar.innerHTML='<button type="button" data-new-note>+ Note</button><button type="button" data-new-event>+ Event</button>';actionBar.querySelector<HTMLButtonElement>('[data-new-note]')!.onclick=e=>{e.stopPropagation();callbacks.onDayAction('team_note',day,team.id,null);};actionBar.querySelector<HTMLButtonElement>('[data-new-event]')!.onclick=e=>{e.stopPropagation();callbacks.onDayAction('internal_event',day,team.id,null);};cell.append(actionBar);
      for(const action of actionsForCell(data.dayActions,day,team.id)){const node=document.createElement('button');node.type='button';node.className=`day-action day-action-${action.kind}`;node.innerHTML=`<span>${action.kind==='team_note'?'NOTE':esc(action.time||'EVENT')}</span><strong>${esc(action.kind==='team_note'?action.detail:action.title)}</strong>`;node.onclick=e=>{e.stopPropagation();callbacks.onDayAction(action.kind,day,team.id,action);};cell.append(node);}
      const rows=visitsForCell(data.visits,day,team.id);rows.forEach((visit,index)=>{cell.append(makeInsertButton(()=>callbacks.onAdd(day,team.id,index,sortOrderForIndex(data.visits,day,team.id,index))));const account=accountById.get(visit.accountId),hold=activeHold(data.clientHolds,visit.accountId);cell.append(makeVisitCard(visit,account,locationForVisit(visit,data.locations),visit.seriesId?seriesById.get(visit.seriesId):undefined,hold,beginDrag,callbacks.onResize,()=>callbacks.onVisitAction(visit,account,hold)));});cell.append(makeInsertButton(()=>callbacks.onAdd(day,team.id,rows.length,sortOrderForIndex(data.visits,day,team.id,rows.length))));grid.append(cell);}
  }
  let drag:{visit:Visit;ghost:HTMLElement;offsetX:number;offsetY:number;moved:boolean}|null=null;
  function beginDrag(event:PointerEvent,visit:Visit,card:HTMLElement):void{if(event.button!==0||(event.target as HTMLElement).closest('[data-resize-handle],[data-visit-action]')||['completed','cancelled','rescheduled','suspended'].includes(String(visit.status).toLowerCase()))return;event.preventDefault();const r=card.getBoundingClientRect(),ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=accountById.get(visit.accountId)?.name??visit.accountId;document.body.append(ghost);drag={visit,ghost,offsetX:event.clientX-r.left,offsetY:event.clientY-r.top,moved:false};place(event.clientX,event.clientY);
    const move=(e:PointerEvent)=>{if(!drag)return;e.preventDefault();drag.moved=true;place(e.clientX,e.clientY);};const end=(e:PointerEvent)=>{if(!drag)return;const current=drag;drag=null;current.ghost.remove();unwire();if(!current.moved)return;const el=document.elementFromPoint(e.clientX,e.clientY);if(el?.closest('[data-basket-drop]')){void callbacks.onQueue(current.visit.id);return;}const target=el?.closest<HTMLElement>('[data-schedule-cell]');const date=target?.dataset.date,teamId=target?.dataset.teamId;if(date&&teamId)void callbacks.onMove({visitId:current.visit.id,date:date as IsoDate,teamId,sortOrder:nextSortOrder(data.visits,date,teamId)});};const cancel=()=>{if(drag){drag.ghost.remove();drag=null;}unwire();};const unwire=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);window.removeEventListener('pointercancel',cancel);};window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end,{once:true});window.addEventListener('pointercancel',cancel,{once:true});cleanup.push(unwire);
  }
  function place(x:number,y:number){if(!drag)return;drag.ghost.style.left=`${x-drag.offsetX}px`;drag.ghost.style.top=`${y-drag.offsetY}px`;}
  return{destroy(){cleanup.forEach(fn=>fn());if(drag?.ghost)drag.ghost.remove();container.innerHTML='';}};
}
function makeInsertButton(onClick:()=>void):HTMLElement{const wrap=document.createElement('div');wrap.className='insert-zone';const btn=document.createElement('button');btn.type='button';btn.className='additional-trigger';btn.title='Add an additional visit here';btn.innerHTML='<b>+</b><span>Additional visit</span>';btn.onclick=e=>{e.stopPropagation();onClick();};wrap.append(btn);return wrap;}
function makeVisitCard(visit:Visit,account:Account|undefined,location:ServiceLocation|null,series:ScheduleSeries|undefined,hold:ClientServiceHold|null,begin:(e:PointerEvent,v:Visit,c:HTMLElement)=>void,onResize:(input:ResizeVisitInput)=>Promise<void>,onAction:()=>void):HTMLElement{
  const status=String(visit.status).toLowerCase(),locked=['completed','cancelled','rescheduled','suspended'].includes(status);const card=document.createElement('article');card.className=`visit-card visit-${visit.visitType} status-${status}${visit.recurrenceManualOverride?' recurrence-exception':''}${hold?' do-not-service':''}`;card.dataset.visitId=visit.id;card.style.setProperty('--visit-height',`${Math.max(58,Math.min(150,58+Math.max(0,visit.estimatedMinutes-60)/15*4))}px`);
  const duration=visit.estimatedMinutes?`${visit.estimatedMinutes} min`:'Duration unset';const badges=[visit.visitType==='additional'?'<span class="visit-badge">A</span>':'',series?`<span class="recurrence-badge" title="${esc(recurrenceLabel(series))}${visit.recurrenceManualOverride?' · this visit is a manual exception':''}">↻</span>`:'',hold?'<span class="dns-badge">DO NOT SERVICE</span>':'',status!=='scheduled'?`<span class="status-badge-v2">${esc(status.toUpperCase())}</span>`:''].join('');
  card.innerHTML=`<div class="visit-card-topline"><strong>${esc(account?.name??visit.accountId)}</strong><span class="visit-badges">${badges}<button type="button" data-visit-action class="visit-action-button" aria-label="Visit actions">•••</button></span></div><div class="visit-location">${esc(location?.address||'Address not linked')}</div><div class="visit-suburb">${esc(location?.suburb||'')}</div><div class="visit-duration">${duration}</div>${locked?'':'<span class="resize-handle" data-resize-handle title="Drag to change duration"></span>'}`;
  card.addEventListener('pointerdown',e=>begin(e,visit,card));card.querySelector<HTMLButtonElement>('[data-visit-action]')!.onclick=e=>{e.stopPropagation();onAction();};const handle=card.querySelector<HTMLElement>('[data-resize-handle]');if(handle)handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();const startY=event.clientY,start=visit.estimatedMinutes||60;let current=start;const move=(e:PointerEvent)=>{e.preventDefault();current=normaliseDuration(start+Math.round((e.clientY-startY)/10)*15);card.querySelector<HTMLElement>('.visit-duration')!.textContent=`${current} min`;card.style.setProperty('--visit-height',`${Math.max(58,Math.min(150,58+Math.max(0,current-60)/15*4))}px`);};const end=()=>{off();if(current!==visit.estimatedMinutes)void onResize({visitId:visit.id,estimatedMinutes:current});};const off=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end);};window.addEventListener('pointermove',move,{passive:false});window.addEventListener('pointerup',end,{once:true});});return card;
}
function esc(v:string):string{return String(v).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]??ch));}
