import { supabase } from '../../lib/supabase.js';
import type { Account, AdditionalVisitInput, BusinessService, ClientServiceHold, MoveVisitInput, PlaceQueueItemInput, ResizeVisitInput, ScheduleDayAction, ScheduleQueueItem, ScheduleSeries, ScheduleSeriesSlot, ScheduleWeek, ServiceAgreement, ServiceLocation, Team, Visit } from '../../domain/types.js';
import type { CancelMode, DayActionInput, RescheduleMissedInput } from '../../domain/operations.js';
import { addDays } from '../../domain/dates.js';
import { billingDispositionFromPayload, serviceLocationIdFromLegacyPayload, visitTypeFromPayload } from '../../domain/schedule.js';

type JsonObject=Record<string,unknown>;
function payloadObject(value:unknown):JsonObject{return value&&typeof value==='object'&&!Array.isArray(value)?value as JsonObject:{};}
const accountSelect='id,name,status,contact_name,email,phone';
const locationSelect='id,customer_id,site_name,address,suburb,access_notes,instructions,active';
const teamSelect='id,name,active,capacity_hours,buffer_hours,created_at';
const visitSelect='id,visit_date,client_id,team_id,status,estimated_hours,sort_order,service_ids,payload,updated_at';
const queueSelect='id,client_id,service_site_id,source_schedule_job_id,original_date,original_team_id,estimated_minutes,service_ids,item_type,billing_disposition,reason,payload';
const occurrenceSelect='schedule_job_id,queue_item_id,series_id,slot_id,occurrence_date,planned_date,manual_override,status';
const seriesSelect='id,client_id,service_site_id,status,frequency,anchor_date,payload';
const slotSelect='id,series_id,weekday,monthly_ordinal,default_team_id,estimated_minutes,service_ids,payload';
const holdSelect='client_id,active,reason,note,updated_at';
const dayActionSelect='id,calendar_date,team_id,kind,title,detail,calendar_time,status,updated_at';

export async function loadWeek(businessId:string,weekStart:ScheduleWeek['weekStart']):Promise<ScheduleWeek>{
  const started=performance.now(),weekEnd=addDays(weekStart,6);
  const {data,error}=await supabase.rpc('tuinbooks_v2_load_schedule_week',{p_business_id:businessId,p_week_start:weekStart});
  if(error){if(/does not exist|schema cache|PGRST20[25]|42883/i.test(String(error?.message??error)))throw new Error('The TuinBooks v2 release migration has not been installed in this database.');throw error;}
  const raw=data??{},rawVisits:any[]=Array.isArray(raw.visits)?raw.visits:[],rawQueue:any[]=Array.isArray(raw.queue_items)?raw.queue_items:[],occurrenceRows:any[]=Array.isArray(raw.occurrences)?raw.occurrences:[],seriesRows:any[]=Array.isArray(raw.series)?raw.series:[],slotRows:any[]=Array.isArray(raw.slots)?raw.slots:[];
  const occurrenceByJob=new Map(occurrenceRows.filter(r=>r.schedule_job_id).map(r=>[String(r.schedule_job_id),r])),occurrenceByQueue=new Map(occurrenceRows.filter(r=>r.queue_item_id).map(r=>[String(r.queue_item_id),r]));
  const series:ScheduleSeries[]=seriesRows.map((r:any)=>({id:String(r.id),businessId,accountId:String(r.client_id),serviceLocationId:r.service_site_id?String(r.service_site_id):null,status:String(r.status),frequency:String(r.frequency) as ScheduleSeries['frequency'],anchorDate:String(r.anchor_date) as ScheduleSeries['anchorDate'],slots:slotRows.filter((slot:any)=>String(slot.series_id)===String(r.id)).map((slot:any):ScheduleSeriesSlot=>({id:String(slot.id),seriesId:String(slot.series_id),weekday:Number(slot.weekday),monthlyOrdinal:slot.monthly_ordinal==null?null:Number(slot.monthly_ordinal),defaultTeamId:String(slot.default_team_id||''),estimatedMinutes:Number(slot.estimated_minutes??60),serviceIds:Array.isArray(slot.service_ids)?slot.service_ids.filter((x:unknown):x is string=>typeof x==='string'):[],payload:payloadObject(slot.payload)})),payload:payloadObject(r.payload)}));
  const teams:Team[]=(Array.isArray(raw.teams)?raw.teams:[]).map((r:any)=>({id:String(r.id),businessId,name:String(r.name),active:r.active!==false,capacityHours:Number(r.capacity_hours??8),bufferHours:Number(r.buffer_hours??1)}));
  const accounts:Account[]=(Array.isArray(raw.accounts)?raw.accounts:[]).map((r:any)=>({id:String(r.id),businessId,name:String(r.name),status:String(r.status),contactName:String(r.contact_name??''),phone:String(r.phone??''),email:String(r.email??'')}));
  const locations:ServiceLocation[]=(Array.isArray(raw.locations)?raw.locations:[]).map((r:any)=>({id:String(r.id),businessId,accountId:String(r.customer_id),siteName:String(r.site_name??''),address:String(r.address??''),suburb:String(r.suburb??''),accessNotes:String(r.access_notes??''),instructions:String(r.instructions??''),active:r.active!==false}));
  const services:BusinessService[]=(Array.isArray(raw.services)?raw.services:[]).map((r:any)=>({id:String(r.id),businessId,name:String(r.name??r.id??'Service'),notes:String(r.notes??''),active:r.active!==false}));
  const agreements:ServiceAgreement[]=(Array.isArray(raw.agreements)?raw.agreements:[]).map((r:any)=>({id:String(r.id),businessId,accountId:String(r.client_id),serviceLocationId:String(r.service_site_id),status:String(r.status??'draft'),startDate:r.start_date?String(r.start_date) as ServiceAgreement['startDate']:null,endDate:r.end_date?String(r.end_date) as ServiceAgreement['endDate']:null,frequency:String(r.frequency??'weekly') as ServiceAgreement['frequency'],weekdays:Array.isArray(r.weekdays)?r.weekdays.map(Number):[],monthlyOrdinal:r.monthly_ordinal==null?null:Number(r.monthly_ordinal),defaultTeamId:String(r.default_team_id??''),estimatedMinutes:Number(r.estimated_minutes??60),serviceIds:Array.isArray(r.service_ids)?r.service_ids.map(String):[],notes:String(r.notes??''),monthlyFee:r.monthly_fee==null?null:Number(r.monthly_fee),scheduleSeriesId:r.schedule_series_id?String(r.schedule_series_id):null,version:Number(r.version??0),updatedAt:r.updated_at?String(r.updated_at):null}));
  const visits:Visit[]=rawVisits.map((r:any)=>{const payload=payloadObject(r.payload),occ=occurrenceByJob.get(String(r.id));return{id:String(r.id),businessId,date:String(r.visit_date) as Visit['date'],accountId:String(r.client_id),serviceLocationId:serviceLocationIdFromLegacyPayload(payload),teamId:String(r.team_id),status:String(r.status),estimatedMinutes:Math.max(0,Math.round(Number(r.estimated_hours??0)*60)),sortOrder:Number(r.sort_order??99),serviceIds:Array.isArray(r.service_ids)?r.service_ids.filter((x:unknown):x is string=>typeof x==='string'):[],visitType:visitTypeFromPayload(payload),billingDisposition:billingDispositionFromPayload(payload),seriesId:occ?.series_id?String(occ.series_id):null,seriesSlotId:occ?.slot_id?String(occ.slot_id):null,occurrenceDate:occ?.occurrence_date?String(occ.occurrence_date) as Visit['occurrenceDate']:null,recurrenceManualOverride:occ?.manual_override===true,payload,updatedAt:r.updated_at?String(r.updated_at):null};});
  const queueItems:ScheduleQueueItem[]=rawQueue.map((r:any)=>{const occ=occurrenceByQueue.get(String(r.id));return{id:String(r.id),businessId,accountId:String(r.client_id),serviceLocationId:r.service_site_id?String(r.service_site_id):null,sourceVisitId:r.source_schedule_job_id?String(r.source_schedule_job_id):null,seriesId:occ?.series_id?String(occ.series_id):null,seriesSlotId:occ?.slot_id?String(occ.slot_id):null,occurrenceDate:occ?.occurrence_date?String(occ.occurrence_date) as Visit['date']:null,originalDate:r.original_date?String(r.original_date) as Visit['date']:null,originalTeamId:r.original_team_id?String(r.original_team_id):null,estimatedMinutes:Number(r.estimated_minutes??0),serviceIds:Array.isArray(r.service_ids)?r.service_ids.filter((x:unknown):x is string=>typeof x==='string'):[],visitType:String(r.item_type||'routine') as ScheduleQueueItem['visitType'],billingDisposition:String(r.billing_disposition||'routine') as ScheduleQueueItem['billingDisposition'],reason:String(r.reason||'Unscheduled work'),payload:payloadObject(r.payload)};});
  const clientHolds:ClientServiceHold[]=(Array.isArray(raw.holds)?raw.holds:[]).map((r:any)=>({businessId,clientId:String(r.client_id),active:r.active===true,reason:String(r.reason||'Do not service'),note:String(r.note||''),updatedAt:r.updated_at?String(r.updated_at):null}));
  const dayActions:ScheduleDayAction[]=(Array.isArray(raw.day_actions)?raw.day_actions:[]).map((r:any)=>({id:String(r.id),businessId,date:String(r.calendar_date) as ScheduleDayAction['date'],teamId:String(r.team_id),kind:String(r.kind) as ScheduleDayAction['kind'],title:String(r.title||''),detail:String(r.detail||''),time:String(r.calendar_time||''),status:String(r.status||'active'),response:String(r.response||''),resolvedAt:r.resolved_at?String(r.resolved_at):null,updatedAt:r.updated_at?String(r.updated_at):null}));
  console.info(`[TuinBooks v2] Week ready in ${Math.round(performance.now()-started)}ms`,{teams:teams.length,visits:visits.length,queue:queueItems.length,accounts:accounts.length,series:series.length});
  return{weekStart,weekEnd,teams,accounts,locations,services,agreements,visits,queueItems,series,clientHolds,dayActions};
}

export async function loadAdditionalVisitClients(businessId:string):Promise<{accounts:Account[];locations:ServiceLocation[]}>{
  const [a,s]=await Promise.all([supabase.from('customers').select(accountSelect).eq('business_id',businessId).eq('status','active').order('name').limit(1000),supabase.from('service_sites').select(locationSelect).eq('business_id',businessId).eq('active',true).limit(2000)]);if(a.error)throw a.error;if(s.error)throw s.error;
  return{accounts:(a.data??[]).map((r:any)=>({id:String(r.id),businessId,name:String(r.name),status:String(r.status),contactName:String(r.contact_name??''),phone:String(r.phone??''),email:String(r.email??'')})),locations:(s.data??[]).map((r:any)=>({id:String(r.id),businessId,accountId:String(r.customer_id),siteName:String(r.site_name??''),address:String(r.address??''),suburb:String(r.suburb??''),accessNotes:String(r.access_notes??''),instructions:String(r.instructions??''),active:r.active!==false}))};
}

export async function persistVisitMove(businessId:string,move:MoveVisitInput):Promise<void>{
  if(move.scope==='future')await rpc('tuinbooks_v2_move_series_future',{p_business_id:businessId,p_visit_id:move.visitId,p_date:move.date,p_team_id:move.teamId,p_sort_order:move.sortOrder});
  else await rpc('tuinbooks_v2_move_visit',{p_business_id:businessId,p_visit_id:move.visitId,p_date:move.date,p_team_id:move.teamId,p_sort_order:move.sortOrder});
}
export async function persistVisitGroupMove(businessId:string,moves:MoveVisitInput[]):Promise<void>{
  await rpc('tuinbooks_v2_move_visits_group_r13',{p_business_id:businessId,p_moves:moves.map(move=>({visit_id:move.visitId,date:move.date,team_id:move.teamId,sort_order:move.sortOrder}))});
}
export async function persistVisitResize(businessId:string,input:ResizeVisitInput):Promise<void>{await rpc('tuinbooks_v2_resize_visit',{p_business_id:businessId,p_visit_id:input.visitId,p_estimated_minutes:input.estimatedMinutes});}
export async function persistVisitToBasket(businessId:string,visitId:string):Promise<void>{await rpc('tuinbooks_v2_move_visit_to_basket',{p_business_id:businessId,p_visit_id:visitId});}
export async function persistVisitGroupToBasket(businessId:string,visitIds:string[]):Promise<void>{await rpc('tuinbooks_v2_move_visits_to_basket_r13',{p_business_id:businessId,p_visit_ids:visitIds});}
export async function persistQueuePlacement(businessId:string,input:PlaceQueueItemInput):Promise<void>{await rpc('tuinbooks_v2_schedule_queue_item',{p_business_id:businessId,p_queue_item_id:input.queueItemId,p_date:input.date,p_team_id:input.teamId,p_sort_order:input.sortOrder});}
export async function persistAdditionalVisit(businessId:string,input:AdditionalVisitInput):Promise<void>{await rpc('tuinbooks_v2_create_additional_visit',{p_business_id:businessId,p_visit_id:input.id,p_date:input.date,p_team_id:input.teamId,p_sort_order:input.sortOrder,p_client_id:input.accountId,p_service_site_id:input.serviceLocationId,p_task:input.task,p_notes:input.notes});}

export async function persistCancelVisit(businessId:string,visitId:string,mode:CancelMode,reason:string):Promise<void>{await rpc('tuinbooks_v2_cancel_visit',{p_business_id:businessId,p_visit_id:visitId,p_charge:mode==='charge',p_reason:reason});}
export async function persistUndoCancel(businessId:string,visitId:string):Promise<void>{await rpc('tuinbooks_v2_undo_cancel_visit',{p_business_id:businessId,p_visit_id:visitId});}
export async function persistMarkMissed(businessId:string,visitId:string,reason:string):Promise<void>{await rpc('tuinbooks_v2_mark_visit_missed',{p_business_id:businessId,p_visit_id:visitId,p_reason:reason});}
export async function persistResolveMissed(businessId:string,visitId:string,decision:'complete'|'no-return',note:string):Promise<void>{await rpc('tuinbooks_v2_resolve_missed_visit_r12',{p_business_id:businessId,p_visit_id:visitId,p_decision:decision,p_work_record_id:`work-r12-${crypto.randomUUID()}`,p_note:note});}
export async function persistRescheduleMissed(businessId:string,input:RescheduleMissedInput):Promise<void>{await rpc('tuinbooks_v2_reschedule_missed_visit',{p_business_id:businessId,p_visit_id:input.visitId,p_new_visit_id:input.newVisitId,p_date:input.date,p_team_id:input.teamId,p_sort_order:input.sortOrder});}
export async function persistSuspension(businessId:string,visitIds:string[],suspended:boolean,reason:string):Promise<void>{await rpc('tuinbooks_v2_set_visit_suspension',{p_business_id:businessId,p_visit_ids:visitIds,p_suspended:suspended,p_reason:reason});}
export async function persistClientHold(businessId:string,clientId:string,active:boolean,reason:string,note:string):Promise<void>{await rpc('tuinbooks_v2_set_client_service_hold',{p_business_id:businessId,p_client_id:clientId,p_active:active,p_reason:reason,p_note:note});}
export async function persistVisitDoNotService(businessId:string,visitId:string,active:boolean,reason:string,note:string):Promise<void>{await rpc('tuinbooks_v2_set_visit_do_not_service',{p_business_id:businessId,p_visit_id:visitId,p_active:active,p_reason:reason,p_note:note});}
export async function persistDayAction(businessId:string,input:DayActionInput):Promise<void>{await rpc('tuinbooks_v2_save_day_action_r8',{p_business_id:businessId,p_action_id:input.id,p_date:input.date,p_team_id:input.teamId,p_kind:input.kind,p_title:input.title,p_detail:input.detail,p_time:input.time||null,p_response:input.response??'',p_status:input.status??'active'});}
export async function persistRemoveDayAction(businessId:string,actionId:string):Promise<void>{await rpc('tuinbooks_v2_remove_day_action',{p_business_id:businessId,p_action_id:actionId});}

async function tryEnsureRecurrenceHorizon(businessId:string,from:ScheduleWeek['weekStart'],through:ScheduleWeek['weekEnd']):Promise<void>{
  const {error}=await supabase.rpc('tuinbooks_v2_ensure_series_horizon',{p_business_id:businessId,p_from:from,p_through:through});
  if(error&&!isMissingRecurrenceSchema(error)&&!/Admin access required/i.test(String(error.message||'')))throw error;
}
async function rpc(name:string,args:Record<string,unknown>):Promise<void>{const{error}=await supabase.rpc(name,args);if(error){if(/does not exist|schema cache|PGRST202/i.test(String(error.message||'')))throw new Error('The required TuinBooks v2 QA migration has not been installed in this database.');throw error;}}
function isMissingV2Table(error:any):boolean{return !!error&&/schedule_queue_items_v2|does not exist|schema cache|PGRST205|42P01/i.test([error.code,error.message,error.details].map(String).join(' '));}
function isMissingRecurrenceSchema(error:any):boolean{return !!error&&/schedule_(series|occurrences)_v2|schedule_series_slots_v2|tuinbooks_v2_ensure_series_horizon|does not exist|schema cache|PGRST20[25]|42P01|42883/i.test([error.code,error.message,error.details].map(String).join(' '));}
function isMissingOperationalSchema(error:any):boolean{return !!error&&/client_service_holds_v2|schedule_day_actions_v2|does not exist|schema cache|PGRST20[25]|42P01/i.test([error.code,error.message,error.details].map(String).join(' '));}
