import { supabase } from '../../lib/supabase.js';
import type { BusinessService, BusinessSettings, BusinessTeamInput, BusinessWorkspace, FieldPin } from '../../domain/business.js';
import { normaliseBusinessSettings } from '../../domain/business.js';

export async function loadBusinessWorkspace(businessId:string):Promise<BusinessWorkspace>{const{data,error}=await supabase.rpc('tuinbooks_v2_load_business_workspace',{p_business_id:businessId});if(error)throw schemaError(error);const settings:BusinessSettings={name:String(data?.business?.name||data?.settings?.name||''),phone:String(data?.business?.phone||data?.settings?.phone||''),email:String(data?.business?.email||data?.settings?.email||''),address:String(data?.business?.address||data?.settings?.address||''),suburb:String(data?.settings?.suburb??''),province:String(data?.settings?.province??''),vatRegistered:data?.settings?.vatRegistered===true,vatNumber:String(data?.settings?.vatNumber??''),mode:data?.settings?.mode==='planning'?'planning':'financials',weekAStartsOn:data?.settings?.weekAStartsOn??null,invoiceDay:Number(data?.settings?.invoiceDay??28),paymentTermsDays:Number(data?.settings?.paymentTermsDays??7),invoicePrefix:String(data?.settings?.invoicePrefix??'INV-'),statementMessage:String(data?.settings?.statementMessage??'Thank you for your business.'),emailFromName:String(data?.settings?.emailFromName??data?.business?.name??'TuinBooks'),whatsappMessage:String(data?.settings?.whatsappMessage??'Your TuinBooks document is ready.')};return{settings,services:(data?.services??[]).map((r:any)=>({id:String(r.id),name:String(r.name),notes:String(r.notes??''),active:r.active!==false})),teams:(data?.teams??[]).map((r:any)=>({id:String(r.id),name:String(r.name),capacityHours:Number(r.capacity_hours??8),bufferHours:Number(r.buffer_hours??1),active:r.active!==false}))};}

export type AuditLogEntry={createdAt:string;actorUserId:string|null;actorLabel:string;entityType:string;entityId:string;action:string;details:Record<string,unknown>};
export async function loadAuditLog(businessId:string,limit=80):Promise<AuditLogEntry[]>{const{data,error}=await supabase.rpc('tuinbooks_v2_list_audit_log_r17',{p_business_id:businessId,p_limit:limit});if(error)throw error;return(data??[]).map((r:any)=>({createdAt:String(r.created_at??''),actorUserId:r.actor_user_id?String(r.actor_user_id):null,actorLabel:String(r.actor_label??'System'),entityType:String(r.entity_type??''),entityId:String(r.entity_id??''),action:String(r.action??''),details:(r.details&&typeof r.details==='object'&&!Array.isArray(r.details)?r.details:{}) as Record<string,unknown>}));}

export async function saveBusinessSettings(businessId:string,input:BusinessSettings){const s=normaliseBusinessSettings(input);const{error}=await supabase.rpc('tuinbooks_v2_save_business_settings',{p_business_id:businessId,p_settings:s});if(error)throw schemaError(error);}
export async function saveBusinessService(businessId:string,input:BusinessService){const{error}=await supabase.rpc('tuinbooks_v2_save_business_service',{p_business_id:businessId,p_id:input.id,p_name:input.name.trim(),p_notes:input.notes.trim(),p_active:input.active});if(error)throw schemaError(error);}

function normaliseFieldPin(r:any):FieldPin{const pin=String(r?.pin??'');if(pin&&!/^\d{4}$/.test(pin))throw new Error('The mobile PIN service returned an invalid PIN.');return{teamId:String(r?.team_id??''),teamName:String(r?.team_name??''),pin,active:r?.active===true,updatedAt:r?.updated_at?String(r.updated_at):null};}
export async function loadFieldPins(businessId:string):Promise<FieldPin[]>{const{data,error}=await supabase.rpc('tuinbooks_v2_list_field_pins',{p_business_id:businessId});if(error)throw schemaError(error);return(data??[]).map(normaliseFieldPin);}
export async function generateFieldPin(businessId:string,teamId:string):Promise<FieldPin>{const{data,error}=await supabase.rpc('tuinbooks_v2_generate_field_pin',{p_business_id:businessId,p_team_id:teamId});if(error)throw schemaError(error);const r=Array.isArray(data)?data[0]:data;const pin=String(r?.pin??'');if(!/^\d{4}$/.test(pin))throw new Error('PIN creation did not return a permanent 4-digit PIN.');const fresh=await loadFieldPins(businessId);const persisted=fresh.find(p=>p.teamId===teamId&&p.active&&p.pin===pin);if(!persisted)throw new Error('PIN creation did not persist. Refresh was not accepted as success.');return persisted;}
export async function revokeFieldPin(businessId:string,teamId:string):Promise<void>{const{error}=await supabase.rpc('tuinbooks_v2_revoke_field_pin',{p_business_id:businessId,p_team_id:teamId});if(error)throw schemaError(error);const fresh=await loadFieldPins(businessId);if(fresh.some(p=>p.teamId===teamId&&p.active))throw new Error('PIN revoke did not persist.');}

export async function saveBusinessTeam(businessId:string,input:BusinessTeamInput){const{error}=await supabase.rpc('tuinbooks_v2_save_business_team',{p_business_id:businessId,p_id:input.id,p_name:input.name.trim(),p_capacity_hours:input.capacityHours,p_buffer_hours:input.bufferHours,p_active:input.active});if(error)throw schemaError(error);}
function schemaError(error:any):Error{if(/does not exist|schema cache|PGRST20[25]|42883/i.test(String(error?.message??error)))return new Error('The TuinBooks database contract required by this screen is not installed.');return error instanceof Error?error:new Error(String(error?.message??error));}
